import { env } from '../config/env.js';
import { supabaseAdmin } from './supabaseAdmin.js';

// ═══════════════════════════════════════════════════════════════
// Admin Services
// ═══════════════════════════════════════════════════════════════

export async function resetPassword(userId: string, newPassword: string) {
  if (!env.supabase.secretKey) throw new Error('Backend is missing SUPABASE_SECRET_KEY');

  const { error } = await supabaseAdmin.auth.admin.updateUserById(userId, { password: newPassword });
  if (error) throw new Error(`Supabase Admin Error: ${error.message}`);
  return true;
}

export async function sendResetLink(email: string) {
  if (!env.supabase.secretKey) throw new Error('Backend is missing SUPABASE_SECRET_KEY');

  const { error } = await supabaseAdmin.auth.admin.generateLink({
    type: 'recovery',
    email,
  });
  if (error) throw new Error(`Supabase Admin Error: ${error.message}`);
  return true;
}

export async function generateImpersonationLink(userId: string): Promise<string> {
  if (!env.supabase.secretKey) throw new Error('Backend is missing SUPABASE_SECRET_KEY');

  // To impersonate, we first need their email.
  const { data: user, error: userErr } = await supabaseAdmin.auth.admin.getUserById(userId);
  if (userErr || !user.user) throw new Error(`User lookup failed: ${userErr?.message || 'Not found'}`);

  if (!user.user.email) throw new Error('User has no email associated');

  const { data, error } = await supabaseAdmin.auth.admin.generateLink({
    type: 'magiclink',
    email: user.user.email,
  });

  if (error) throw new Error(`Supabase Admin Error: ${error.message}`);
  if (!data.properties?.action_link) throw new Error('No action link generated by Supabase');

  return data.properties.action_link;
}

export async function updateUserAuth(userId: string, updates: { email?: string; user_metadata?: any }) {
  if (!env.supabase.secretKey) throw new Error('Backend is missing SUPABASE_SECRET_KEY');

  const { error } = await supabaseAdmin.auth.admin.updateUserById(userId, updates);
  if (error) throw new Error(`Supabase Admin Error: ${error.message}`);
  return true;
}

export async function deleteAuthUser(userId: string) {
  if (!env.supabase.secretKey) throw new Error('Backend is missing SUPABASE_SECRET_KEY');

  const { error } = await supabaseAdmin.auth.admin.deleteUser(userId);
  if (error) throw new Error(`Supabase Admin Error: ${error.message}`);
  return true;
}

/**
 * Create a new user directly (bypasses invite flow).
 * Creates the Supabase Auth user with email_confirm: true so they can login immediately.
 * The profiles table trigger will auto-create their profile row.
 */
export async function createUser(opts: {
  email: string;
  password: string;
  fullName?: string;
  role?: string;
}): Promise<{ userId: string }> {
  if (!env.supabase.secretKey) throw new Error('Backend is missing SUPABASE_SECRET_KEY');

  // 1. Create the auth user
  const { data, error } = await supabaseAdmin.auth.admin.createUser({
    email: opts.email,
    password: opts.password,
    email_confirm: true, // Skip email verification
    user_metadata: {
      full_name: opts.fullName || opts.email.split('@')[0],
    },
  });

  if (error) throw new Error(`Create user failed: ${error.message}`);
  if (!data.user) throw new Error('User creation returned no user object');

  const userId = data.user.id;

  // 2. Update their profile with role and name (the trigger creates a default row)
  //    Small delay to let the trigger fire
  await new Promise(r => setTimeout(r, 500));

  const updates: Record<string, unknown> = {};
  if (opts.fullName) updates.full_name = opts.fullName;
  if (opts.role) updates.role = opts.role;
  updates.is_active = true;

  // Generate a deterministic avatar so the user has a profile image from day one.
  // DiceBear notionists-neutral style — clean, professional, gender-neutral.
  // If the user later uploads their own avatar via Settings, it overwrites this.
  const DICEBEAR_BASE = 'https://api.dicebear.com/9.x/notionists-neutral';
  const BG_PALETTE = 'b6e3f4,c0aede,d1d4f9,ffd5dc,ffdfbf';
  updates.avatar_url = `${DICEBEAR_BASE}/svg?seed=${encodeURIComponent(opts.email)}&size=256&backgroundColor=${BG_PALETTE}`;

  if (Object.keys(updates).length > 0) {
    const { error: profileErr } = await supabaseAdmin
      .from('profiles')
      .update(updates)
      .eq('id', userId);

    if (profileErr) {
      console.warn(`[Admin] Profile update after create failed: ${profileErr.message}`);
      // Don't throw — the auth user was created, profile will just have defaults
    }
  }

  return { userId };
}
