import { env } from '../config/env.js';
import { supabaseAdmin } from './supabaseAdmin.js';

// ═══════════════════════════════════════════════════════════════
// Admin Services
// ═══════════════════════════════════════════════════════════════

export async function resetPassword(userId: string, newPassword: string) {
  if (!env.supabase.secretKey) throw new Error('Backend is missing SUPABASE_SECRET_KEY');
  
  const { error } = await supabaseAdmin.auth.admin.updateUserById(userId, { password: newPassword });
  if (error) throw new Error(`Supabase Admin Error: ${error.message}`);
  return true;
}

export async function sendResetLink(email: string) {
  if (!env.supabase.secretKey) throw new Error('Backend is missing SUPABASE_SECRET_KEY');
  
  const { error } = await supabaseAdmin.auth.admin.generateLink({
    type: 'recovery',
    email,
  });
  if (error) throw new Error(`Supabase Admin Error: ${error.message}`);
  return true;
}

export async function generateImpersonationLink(userId: string): Promise<string> {
  if (!env.supabase.secretKey) throw new Error('Backend is missing SUPABASE_SECRET_KEY');

  // To impersonate, we first need their email.
  const { data: user, error: userErr } = await supabaseAdmin.auth.admin.getUserById(userId);
  if (userErr || !user.user) throw new Error(`User lookup failed: ${userErr?.message || 'Not found'}`);
  
  if (!user.user.email) throw new Error('User has no email associated');

  const { data, error } = await supabaseAdmin.auth.admin.generateLink({
    type: 'magiclink',
    email: user.user.email,
  });

  if (error) throw new Error(`Supabase Admin Error: ${error.message}`);
  if (!data.properties?.action_link) throw new Error('No action link generated by Supabase');

  return data.properties.action_link;
}

export async function updateUserAuth(userId: string, updates: { email?: string; user_metadata?: any }) {
  if (!env.supabase.secretKey) throw new Error('Backend is missing SUPABASE_SECRET_KEY');
  
  const { error } = await supabaseAdmin.auth.admin.updateUserById(userId, updates);
  if (error) throw new Error(`Supabase Admin Error: ${error.message}`);
  return true;
}

export async function deleteAuthUser(userId: string) {
  if (!env.supabase.secretKey) throw new Error('Backend is missing SUPABASE_SECRET_KEY');
  
  const { error } = await supabaseAdmin.auth.admin.deleteUser(userId);
  if (error) throw new Error(`Supabase Admin Error: ${error.message}`);
  return true;
}
