import type { Phase } from './data';

export const PHASES_4_9: Phase[] = [
  {
    id: 'p4', number: 4, title: 'Delivery Engine Build', owner: 'both', score: [24, 24],
    requirements: [
      { id: 'p4-1', label: 'Create tenant environment', status: 'done', evidence: 'organizations + partner (1:1 map)' },
      { id: 'p4-2', label: 'Create domains', status: 'done', evidence: 'sending_domains (migration 22, fixed 40)' },
      { id: 'p4-3', label: 'Verify DNS', status: 'done', evidence: 'sending_domains.dns_verified' },
      { id: 'p4-4', label: 'Create mailboxes', status: 'done', evidence: 'sending_satellites with mailbox_email' },
      { id: 'p4-5', label: 'Configure routing', status: 'done', evidence: 'Email provider configs (migration 24)' },
      { id: 'p4-6', label: 'Configure suppression enforcement', status: 'done', evidence: 'global + partner contact_suppression' },
      { id: 'p4-7', label: 'Define pacing model', status: 'done', evidence: 'config_table send_pacing_daily_cap + satellites.daily_cap' },
      { id: 'p4-8', label: 'Define warm-up plan', status: 'done', evidence: 'sending_satellites.warmup_* fields' },
      { id: 'p4-9', label: 'Create delivery campaign objects', status: 'done', evidence: 'Engine bundles (migration 33)' },
      { id: 'p4-10', label: 'Create MailWizz customer', status: 'done', evidence: 'Backend MailWizz API integration' },
      { id: 'p4-11', label: 'Create MailWizz lists', status: 'done', evidence: 'Backend MailWizz API integration' },
      { id: 'p4-12', label: 'Assign sending domain', status: 'done', evidence: 'sending_satellites.domain_id FK' },
      { id: 'p4-13', label: 'Confirm infrastructure readiness', status: 'done', evidence: 'sending_satellites.status' },
      { id: 'p4-14', label: 'Deliverability snapshots', status: 'done', evidence: 'deliverability_snapshots — daily per-satellite metrics' },
      { id: 'p4-15', label: 'Deliverability alerts', status: 'done', evidence: 'deliverability_alerts — 7 types, severity, ack' },
      { id: 'p4-16', label: 'Bounce/complaint tracking', status: 'done', evidence: 'signal_event.event_type bounce,complaint' },
      { id: 'p4-17', label: 'Circuit breaker', status: 'done', evidence: 'complaint_circuit_breaker_config (migration 60)' },
      { id: 'p4-18', label: 'Signal event idempotency', status: 'done', evidence: 'Migration 36: dedup' },
      { id: 'p4-19', label: 'Unsubscribe handling', status: 'done', evidence: 'Migration 61: unsubscribe event type' },
      { id: 'p4-20', label: 'Worker infrastructure', status: 'done', evidence: 'worker_deployment_config (migration 59)' },
      { id: 'p4-21', label: 'Queue concurrency controls', status: 'done', evidence: 'queue_concurrency JSONB config' },
      { id: 'p4-22', label: 'Infrastructure UI', status: 'done', evidence: 'superadmin/infrastructure/ + mta-overview/' },
      { id: 'p4-23', label: 'Email Providers UI', status: 'done', evidence: 'superadmin/email-providers/' },
      { id: 'p4-24', label: 'Email Hub UI', status: 'done', evidence: '(main)/email-hub/' },
    ],
  },
  {
    id: 'p5', number: 5, title: 'Pre-Launch Validation', owner: 'axiom', score: [12, 14],
    requirements: [
      { id: 'p5-1', label: 'ICP validation (active, non-overlapping)', status: 'done', evidence: 'icp.status check + icp_manager UI' },
      { id: 'p5-2', label: 'Brief validation per ICP', status: 'done', evidence: 'brief table + superadmin/briefs' },
      { id: 'p5-3', label: 'Belief validation per Brief', status: 'done', evidence: 'belief_gate_snapshot.passed' },
      { id: 'p5-4', label: 'Two competing beliefs exist', status: 'done', evidence: 'belief_competition table' },
      { id: 'p5-5', label: 'No belief mixing per flow', status: 'done', evidence: 'flow.belief_id — one belief per flow' },
      { id: 'p5-6', label: 'Suppression check', status: 'done', evidence: 'Suppression tables + enforcement' },
      { id: 'p5-7', label: 'Infrastructure readiness check', status: 'done', evidence: 'sending_satellites.status + deliverability' },
      { id: 'p5-8', label: 'Routing validation', status: 'done', evidence: 'Email provider routing validation' },
      { id: 'p5-9', label: 'Test batch (internal)', status: 'done', evidence: 'Engine execution worker' },
      { id: 'p5-10', label: 'Test batch (client)', status: 'done', evidence: 'Engine execution worker' },
      { id: 'p5-11', label: 'Reply path functional', status: 'done', evidence: 'Signal event ingestion for reply events' },
      { id: 'p5-12', label: 'Validation workspace UI', status: 'done', evidence: 'superadmin/ai-validation/' },
      { id: 'p5-13', label: 'Authorization decision record', status: 'missing', note: 'No validation_run table with pass/fail' },
      { id: 'p5-14', label: 'Validation run naming convention', status: 'partial', note: 'Convention only, not enforced' },
    ],
  },
  {
    id: 'p6', number: 6, title: 'Controlled Launch', owner: 'axiom', score: [11, 12],
    requirements: [
      { id: 'p6-1', label: 'Start controlled launch', status: 'done', evidence: 'engine-execution-worker' },
      { id: 'p6-2', label: 'Monitor early signals', status: 'done', evidence: 'signal_event + analytics' },
      { id: 'p6-3', label: 'Verify bounce rates', status: 'done', evidence: 'deliverability_snapshots.bounce_rate' },
      { id: 'p6-4', label: 'Verify complaint rates', status: 'done', evidence: 'deliverability_snapshots.complaint_rate' },
      { id: 'p6-5', label: 'Verify reply quality', status: 'done', evidence: 'Reply events in signal_event' },
      { id: 'p6-6', label: 'Monitor system stability', status: 'done', evidence: 'Deliverability alerts with severity' },
      { id: 'p6-7', label: 'Confirm partner handling', status: 'done', evidence: 'Partner management UI' },
      { id: 'p6-8', label: 'Scale eligibility decision', status: 'done', evidence: 'Config thresholds' },
      { id: 'p6-9', label: 'Scale execution', status: 'done', evidence: 'Worker pacing controls' },
      { id: 'p6-10', label: 'Pause if signal degrades', status: 'done', evidence: 'Circuit breaker + alerts' },
      { id: 'p6-11', label: 'Launch workspace UI', status: 'done', evidence: 'Engine execution orchestration' },
      { id: 'p6-12', label: 'Launch naming convention', status: 'partial', note: 'Convention only' },
    ],
  },
  {
    id: 'p7', number: 7, title: 'Learning & Optimization', owner: 'axiom', score: [11, 11],
    requirements: [
      { id: 'p7-1', label: 'Analyze signal by belief', status: 'done', evidence: 'signal_event indexed by belief_id + belief_daily_rollup' },
      { id: 'p7-2', label: 'Run confidence formula', status: 'done', evidence: 'config_table.confidence_formula_v1' },
      { id: 'p7-3', label: 'Run gate check', status: 'done', evidence: 'belief_gate_snapshot with passed boolean' },
      { id: 'p7-4', label: 'Make promotion/demotion decision', status: 'done', evidence: 'belief_promotion_log' },
      { id: 'p7-5', label: 'Update allocation weights', status: 'done', evidence: 'belief.allocation_weight + belief_competition' },
      { id: 'p7-6', label: 'Write local knowledge', status: 'done', evidence: 'brain_memories + brain_reflections + brain_dream_logs' },
      { id: 'p7-7', label: 'Knowledge gap tracking', status: 'done', evidence: 'knowledge_gaps table' },
      { id: 'p7-8', label: 'Generate governed decisions', status: 'done', evidence: 'learning-loop-worker + dream-state-worker' },
      { id: 'p7-9', label: 'Update rules based on signal', status: 'done', evidence: 'learning_rules + learning_history + brain_learning_events' },
      { id: 'p7-10', label: 'Learning workspace UI', status: 'done', evidence: '(main)/learning/ + superadmin/analytics/' },
      { id: 'p7-11', label: 'Brain control UI', status: 'done', evidence: '(main)/brain-control/ + brain-chat/' },
    ],
  },
  {
    id: 'p8', number: 8, title: 'Reporting & Partner Management', owner: 'axiom', score: [11, 13],
    requirements: [
      { id: 'p8-1', label: 'Dashboard with belief performance', status: 'done', evidence: 'superadmin/belief-dashboard/ + belief_daily_rollup' },
      { id: 'p8-2', label: 'Partner-level analytics', status: 'done', evidence: 'partner_daily_rollup (migration 27)' },
      { id: 'p8-3', label: 'Analytics events tracking', status: 'done', evidence: 'analytics_events table + analytics worker' },
      { id: 'p8-4', label: 'Decision logs visible', status: 'done', evidence: 'belief_promotion_log + brain_learning_events' },
      { id: 'p8-5', label: 'Meeting tracking', status: 'done', evidence: 'meeting table (migration 20)' },
      { id: 'p8-6', label: 'Partner management UI', status: 'done', evidence: 'superadmin/organizations/ + dashboard/' },
      { id: 'p8-7', label: 'Signal quality reporting', status: 'done', evidence: 'deliverability_snapshots with computed rates' },
      { id: 'p8-8', label: 'Issue management', status: 'done', evidence: 'deliverability_alerts with severity + ack' },
      { id: 'p8-9', label: 'Feedback loop capture', status: 'done', evidence: 'Brain learning events + reflections' },
      { id: 'p8-10', label: 'Reporting dashboard UI', status: 'done', evidence: 'superadmin/analytics/ + (main)/analytics/' },
      { id: 'p8-11', label: 'Portal (partner-facing) UI', status: 'done', evidence: '(main)/portal/' },
      { id: 'p8-12', label: 'Decision export', status: 'missing', note: 'No explicit export function' },
      { id: 'p8-13', label: 'Contact export', status: 'missing', note: 'No explicit export function' },
    ],
  },
  {
    id: 'p9', number: 9, title: 'De-Activation & Handover', owner: 'axiom', score: [1, 6],
    requirements: [
      { id: 'p9-1', label: 'Revoke Delivery Engine assets', status: 'partial', note: 'Can pause but no revocation flow' },
      { id: 'p9-2', label: 'Terminal state transition', status: 'missing', note: 'No terminal value on partner.status' },
      { id: 'p9-3', label: 'Data export (partner data + rejected)', status: 'missing', note: 'No export pipeline' },
      { id: 'p9-4', label: 'IP boundary enforcement', status: 'partial', note: 'Org-scoped but no IP handover' },
      { id: 'p9-5', label: 'Audit log generation', status: 'partial', note: 'Logs exist but no master export' },
      { id: 'p9-6', label: 'De-Activation UI', status: 'missing', note: 'No offboarding UI' },
    ],
  },
];
