import type { Phase } from './data';

export const PHASES: Phase[] = [
  {
    id: 'p0', number: 0, title: 'Partner Qualification & Activation', owner: 'axiom', score: [7, 10],
    requirements: [
      { id: 'p0-1', label: 'Create partner record', status: 'done', evidence: 'partner table (migration 12)' },
      { id: 'p0-2', label: 'Create offer record', status: 'done', evidence: 'offer table (migration 12)' },
      { id: 'p0-3', label: 'Partner status tracking', status: 'done', evidence: 'partner.status enum' },
      { id: 'p0-4', label: 'Offer status tracking', status: 'done', evidence: 'offer.status enum' },
      { id: 'p0-5', label: 'Client & Offer Setup UI', status: 'done', evidence: 'superadmin/organizations/' },
      { id: 'p0-6', label: 'Artifact & Intake Uploads UI', status: 'done', evidence: 'superadmin/kb-onboarding/' },
      { id: 'p0-7', label: 'Compliance constraint tracking', status: 'done', evidence: 'global_contact_suppression + partner_contact_suppression' },
      { id: 'p0-8', label: 'Booking path verification', status: 'partial', note: 'Manual process, no explicit table' },
      { id: 'p0-9', label: 'Activation status (approved/rejected)', status: 'partial', note: 'No explicit approved/rejected values on partner.status' },
      { id: 'p0-10', label: 'Revenue agreement tracking', status: 'missing', note: 'External/manual' },
    ],
  },
  {
    id: 'p1', number: 1, title: 'Onboarding & Intake', owner: 'axiom', score: [12, 15],
    requirements: [
      { id: 'p1-1', label: 'Onboarding questionnaire', status: 'done', evidence: 'kb_questionnaire_responses (migration 62)' },
      { id: 'p1-2', label: 'Intake artifact upload', status: 'done', evidence: 'kb_artifact_uploads (migration 62)' },
      { id: 'p1-3', label: 'Knowledge base upload', status: 'done', evidence: 'kb_documents + kb_sections (migration 17)' },
      { id: 'p1-4', label: 'KB extraction & processing', status: 'done', evidence: 'kb_extraction_jobs + kb-extraction-worker' },
      { id: 'p1-5', label: 'ICP segment definition', status: 'done', evidence: 'kb_icp_segments (migration 62)' },
      { id: 'p1-6', label: 'Master sections / KB structure', status: 'done', evidence: 'kb_master_sections (migration 62)' },
      { id: 'p1-7', label: 'KB form configuration', status: 'done', evidence: 'kb_form_config (migration 65)' },
      { id: 'p1-8', label: 'KB grading agent', status: 'done', evidence: 'Migration 63: kb_grader_agent' },
      { id: 'p1-9', label: 'Brain hydration agent', status: 'done', evidence: 'Migration 64: brain_hydrator_agent' },
      { id: 'p1-10', label: 'Suppression rules definition', status: 'done', evidence: 'partner_contact_suppression + global_contact_suppression' },
      { id: 'p1-11', label: 'KB Onboarding UI', status: 'done', evidence: '(main)/kb-onboarding/ + superadmin/kb-onboarding/' },
      { id: 'p1-12', label: 'KB Review UI', status: 'done', evidence: '(main)/kb-review/ + superadmin/kb-review/' },
      { id: 'p1-13', label: 'CRM / booking flow map', status: 'partial', note: 'No explicit table — JSONB or manual' },
      { id: 'p1-14', label: 'Intake completeness pass/fail', status: 'missing', note: 'No explicit field on partner/offer' },
      { id: 'p1-15', label: 'KB Manager UI', status: 'done', evidence: '(main)/kb-manager/' },
    ],
  },
  {
    id: 'p2', number: 2, title: 'Data Engine Build', owner: 'refinery', score: [13, 17],
    requirements: [
      { id: 'p2-1', label: 'Define ICP segments', status: 'done', evidence: 'segments table + filter builder + validate/execute/export' },
      { id: 'p2-2', label: 'Load suppression lists', status: 'done', evidence: '_bounced flag + engagement writeback (bounce/complaint/unsub)' },
      { id: 'p2-3', label: 'Upload monthly UP file', status: 'done', evidence: 'S3 sources → ingestion → CSV/Parquet/GZ parsing with retry' },
      { id: 'p2-4', label: 'Run UP prep', status: 'done', evidence: 'ingestion_jobs with retry, progress, _search_text, tolerance' },
      { id: 'p2-5', label: 'Select active up_prep_version', status: 'partial', note: 'Tagged by _ingestion_job_id but no version toggle UI' },
      { id: 'p2-6', label: 'Run ICP classification', status: 'done', evidence: '_segment_ids array with arrayConcat/arrayFilter tagging' },
      { id: 'p2-7', label: 'Run buying unit assignment', status: 'partial', note: 'company_domain grouping exists, no explicit buying_unit table' },
      { id: 'p2-8', label: 'Run identity validation', status: 'done', evidence: 'business_email_validation_status + personal_emails_validation_status' },
      { id: 'p2-9', label: 'Run role classification', status: 'done', evidence: 'job_title_normalized, seniority_level, department columns' },
      { id: 'p2-10', label: 'Run buyer stage classification', status: 'missing', note: 'No buyer_stage column — 0 results in codebase search' },
      { id: 'p2-11', label: 'Run timing/readiness evaluation', status: 'partial', note: 'AI List Segmentation has engagementReadiness — not persisted to CH' },
      { id: 'p2-12', label: 'Run person-level decisioning', status: 'missing', note: 'No contact_now/delay/suppress column — decisions implicit only' },
      { id: 'p2-13', label: 'Select approved contact records', status: 'done', evidence: 'target_lists generated from segments with dedup-check' },
      { id: 'p2-14', label: 'Run business email hygiene', status: 'done', evidence: 'Verify550 (26 cats) + standalone verifier (8 checks)' },
      { id: 'p2-15', label: 'Re-check suppression', status: 'done', evidence: 'reverify_enabled + reverify_days_threshold + reverify-scheduler' },
      { id: 'p2-16', label: 'Generate approved contact pool', status: 'done', evidence: 'target_lists + S3 export + MailWizz push + multi-MTA push' },
      { id: 'p2-17', label: 'Record rejected contact memory', status: 'partial', note: 'Flagged in UP (_bounced=1) but no dedicated rejected pool export' },
    ],
  },
  {
    id: 'p3', number: 3, title: 'MarketWriter Build', owner: 'axiom', score: [24, 27],
    requirements: [
      { id: 'p3-1', label: 'Create offer record', status: 'done', evidence: 'offer table (migration 12)' },
      { id: 'p3-2', label: 'Create VP worksheet', status: 'partial', note: 'No explicit vp_worksheet table — may live in KB/JSONB' },
      { id: 'p3-3', label: 'Upload Product/Service KB', status: 'done', evidence: 'kb_documents + kb_sections + KB pipeline' },
      { id: 'p3-4', label: 'Build angle inventory', status: 'done', evidence: 'offer_angles (migration 19)' },
      { id: 'p3-5', label: 'Build angle coverage map', status: 'done', evidence: 'offer_angle_hooks (migration 19)' },
      { id: 'p3-6', label: 'Create Brief per ICP', status: 'done', evidence: 'brief table with icp_id FK' },
      { id: 'p3-7', label: 'Validate Brief', status: 'done', evidence: 'superadmin/briefs/' },
      { id: 'p3-8', label: 'Generate Flow A', status: 'done', evidence: 'flow table linked to belief_id' },
      { id: 'p3-9', label: 'Generate Flow B', status: 'done', evidence: 'Same flow table — two beliefs per brief via belief_competition' },
      { id: 'p3-10', label: 'Lock one belief per flow', status: 'done', evidence: 'belief.lane (champion/challenger) + belief_competition' },
      { id: 'p3-11', label: 'Flow steps (subject A/B, body)', status: 'done', evidence: 'flow_step with subject_a, subject_b, body_html, body_text' },
      { id: 'p3-12', label: 'Configure testing plan', status: 'done', evidence: 'config_table (promotion_min_sample_size, allocation weights)' },
      { id: 'p3-13', label: 'Configure extension rules', status: 'partial', note: 'No explicit table' },
      { id: 'p3-14', label: 'Configure reply meaning rules', status: 'partial', note: 'No explicit table — may be in Brain/agent config' },
      { id: 'p3-15', label: 'Belief status lifecycle', status: 'done', evidence: 'belief.status: HYP→TEST→SW→IW→RW→GW→PAUSED' },
      { id: 'p3-16', label: 'Belief confidence score', status: 'done', evidence: 'belief.confidence_score NUMERIC(6,5)' },
      { id: 'p3-17', label: 'Belief allocation weight', status: 'done', evidence: 'belief.allocation_weight NUMERIC(6,5)' },
      { id: 'p3-18', label: 'Belief promotion log', status: 'done', evidence: 'belief_promotion_log table' },
      { id: 'p3-19', label: 'Belief gate snapshot', status: 'done', evidence: 'belief_gate_snapshot table' },
      { id: 'p3-20', label: 'Signal events', status: 'done', evidence: 'signal_event table with 9 event types' },
      { id: 'p3-21', label: 'Asset production', status: 'done', evidence: 'asset table — email, landing_page, social_post, ad_copy' },
      { id: 'p3-22', label: 'MarketWriter Workspace UI', status: 'done', evidence: 'superadmin/briefs/ + belief-dashboard/ + writer/' },
      { id: 'p3-23', label: 'Belief Dashboard UI', status: 'done', evidence: 'superadmin/belief-dashboard/' },
      { id: 'p3-24', label: 'Confidence formula config', status: 'done', evidence: 'config_table key confidence_formula_v1' },
      { id: 'p3-25', label: 'Daily rollup analytics', status: 'done', evidence: 'belief_daily_rollup + partner_daily_rollup (migration 27)' },
      { id: 'p3-26', label: 'Brain memories / reflections', status: 'done', evidence: 'brain_memories, brain_reflections, brain_dream_logs' },
      { id: 'p3-27', label: 'Learning events', status: 'done', evidence: 'brain_learning_events (migration 47)' },
    ],
  },
];
